load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//phaser:copts.bzl", "PHASER_COPTS")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "phaser_lib",
    srcs = [
        "enum_gen.cc",
        "gen.cc",
        "message_gen.cc",
    ],
    copts = PHASER_COPTS,
    hdrs = [
        "enum_gen.h",
        "gen.h",
        "message_gen.h",
    ],
    deps = [
        "//phaser:options_cc_proto",
        "@com_google_absl//absl/container:flat_hash_map",
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/strings:str_format",
        "@com_google_protobuf//:protoc_lib",
    ],
)

cc_binary(
    name = "phaser",
    srcs = [
        "main.cc",
    ],
    copts = PHASER_COPTS,
    deps = [
        ":phaser_lib",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
        "@com_google_protobuf//:protoc_lib",
    ],
)
